init:
  - appveyor version

matrix:
  fast_finish: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

environment:
  matrix:
      
    - job_name: Windows
      platform: x64
      appveyor_build_worker_image: Visual Studio 2022
      configuration: Release
      job_group: Building
      
    - job_name: Darwin
      platform: x64
      appveyor_build_worker_image: macos-monterey
      configuration: Release
      job_group: Building
      
    - job_name: Linux
      platform: x64
      appveyor_build_worker_image: Ubuntu2204
      configuration: Release
      job_group: Building
      
    - job_name: Package
      job_depends_on: Building
      
# job-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Windows

    build_script:
      - cmd: echo This is Windows-specific build script

  -
    matrix:
      only:
        - job_name: Darwin

    build_script:
      - sh: echo This is Mac-specific build script
        
  - matrix:
      only:
        - job_name: Linux

    build_script:
      - sh: echo This is Linux-specific build script
        
  - matrix:
      only:
        - job_name: Package

    build_script:
      - sh: echo This is Packaging script
