init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq "true") { $env:TAG_VERSION = "$env:APPVEYOR_REPO_TAG_NAME.$env:APPVEYOR_BUILD_NUMBER" } else { $env:TAG_VERSION = "v0.1.0.$env:APPVEYOR_BUILD_NUMBER-alpha" }
  - ps: $env:TAG_VERSION = $env:TAG_VERSION -replace 'v',''
  - ps: Write-Host "Setting version to '$env:TAG_VERSION'"
  - ps: Update-AppveyorBuild -Version "$env:TAG_VERSION"

environment:
  matrix:
  - job_name: Windows Build
    platform: x64
    appveyor_build_worker_image: Visual Studio 2019
    configuration: Release
  - job_name: Linux Build
    platform: x64
    appveyor_build_worker_image: Ubuntu
    configuration: Release
  - job_name: MacOS Build
    platform: x64
    appveyor_build_worker_image: macos-mojave
    configuration: Release

#matrix:
#  fast_finish: true

before_build:
  - git submodule update --init --recursive

# job specific
for:
  -
    matrix:
      only:
        - job_name: Windows Build
    before_build:
      - cmd: chcp 65001
      - cmd: git clean -fxd nuget/
    build_script:
      - cmd: cd nuget
      - cmd: pwsh ./BuildWindows.ps1
    artifacts:
      - path: nuget/artifacts
        name: Nupkgs
        type: Auto
  -
    matrix:
      only:
        - job_name: Linux Build
    before_build:
      - cmd: git clean -fxd nuget/
    build_script:
      - cmd: cd nuget
      - cmd: pwsh ./BuildUbuntu18.ps1
    artifacts:
      - path: nuget/artifacts
        name: Nupkgs
        type: Auto
  -
    matrix:
      only:
        - job_name: MacOS Build
    before_build:
      - cmd: git clean -fxd nuget/
    build_script:
      - cmd: cd nuget
      - cmd: pwsh BuildOSX.ps1
    artifacts:
      - path: nuget/artifacts
        name: Nupkgs
        type: Auto