init:
  - appveyor version

matrix:
  fast_finish: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

environment:
  matrix:
      
    - job_name: Windows
      platform: x64
      appveyor_build_worker_image: Visual Studio 2022
      configuration: Release
      job_group: Building
      
    - job_name: Darwin
      platform: x64
      appveyor_build_worker_image: macos-monterey
      configuration: Release
      job_group: Building
      
    - job_name: Linux
      platform: x64
      appveyor_build_worker_image: Ubuntu2004
      configuration: Release
      job_group: Building
      
    - job_name: Package
      job_depends_on: Building
      
# job-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Windows

    before_build:
      - cmd: chcp 65001
      - cmd: git submodule update --init --recursive
    build_script:
      - cmd: cd nuget
      - cmd: git clean -fxd .
      - pwsh: .\BuildWindows.ps1  

  -
    matrix:
      only:
        - job_name: Darwin

    before_build:
      - sh: git submodule update --init --recursive
    build_script:
      - sh: cd nuget
      - pwsh: ./BuildOSX.ps1
        
  - matrix:
      only:
        - job_name: Linux

    before_build:
      - sh: git submodule update --init --recursive
    build_script:
      - sh: cd nuget
      - pwsh: .\BuildUbuntu.ps1
        
  - matrix:
      only:
        - job_name: Package

    build_script:
      - cmd: echo This is Packaging script


artifacts:
  - path: 'nuget/artifacts/*/runtimes/*/native/*OpenJpegDotNet*'
    name: 'Library'
    type: Auto